//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyHelpline.QuotesTool.Calculator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class QuoteRunnerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static QuoteRunnerSettings defaultInstance = ((QuoteRunnerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QuoteRunnerSettings())));
        
        public static QuoteRunnerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EnergyHelpline Quote Team")]
        public string QuoteSignature {
            get {
                return ((string)(this["QuoteSignature"]));
            }
            set {
                this["QuoteSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotificationTemplate.htm")]
        public string TemplateName {
            get {
                return ((string)(this["TemplateName"]));
            }
            set {
                this["TemplateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please find below the cheapest quote our system has generated based on your usage" +
            ". <br /><br /> Date: {0} <br /> Gas Usage: {1} kWh<br /> Electricity Usage: {2} " +
            "kWh <br /> Cheapest Tariff: {3} <br /> Annual Cost: £{4}")]
        public string HtmlPayload {
            get {
                return ((string)(this["HtmlPayload"]));
            }
            set {
                this["HtmlPayload"] = value;
            }
        }
    }
}
